trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '20.10.3'

- script: docker run --rm --volume ${PWD}:/work --workdir /work ghdl/vunit:gcc python3 /work/scripts/scripts/test.py
  displayName: 'Run tests'
