trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: mirror-git-repository-vsts-task@1
  inputs:
    sourceGitRepositoryUri: '$(Build.Repository.Uri)'
    sourceGitRepositoryPersonalAccessToken: '$(DEVOPS_TOKEN)'
    destinationGitRepositoryUri: 'https://github.com/chsag/vhdl-scripts'
    destinationGitRepositoryPersonalAccessToken: '$(GITHUB_TOKEN)'
