name: Cyclone10LP

on:
  schedule:
    - cron: '22 7 * * *'
  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ]

env:
  REGISTRY: ghcr.io

jobs:
  docker:
    strategy:
      matrix:
        fpga: [ cyclone10lp, max ]
  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.fpga }}-dev-container
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
  
      - name: Login to ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.fpga }}.dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
